/*
 * generated by Xtext 2.27.0
 */
package ghidra.xtext.sleigh;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SleighRuntimeModule extends AbstractSleighRuntimeModule {
}
