/*
 * generated by Xtext 2.27.0
 */
package ghidra.xtext.sleigh;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SleighStandaloneSetup extends SleighStandaloneSetupGenerated {

	public static void doSetup() {
		new SleighStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
