/*
 * generated by Xtext 2.27.0
 */
package ghidra.xtext.sleigh.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class SleighScopeProvider extends AbstractSleighScopeProvider {

}
