/*
 * generated by Xtext 2.27.0
 */
package ghidra.xtext.sleigh.ide

import com.google.inject.Guice
import ghidra.xtext.sleigh.SleighRuntimeModule
import ghidra.xtext.sleigh.SleighStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SleighIdeSetup extends SleighStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SleighRuntimeModule, new SleighIdeModule))
	}
	
}
