/*
 * generated by Xtext 2.27.0
 */
package ghidra.xtext.sleigh.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ghidra.xtext.sleigh.SleighRuntimeModule;
import ghidra.xtext.sleigh.SleighStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SleighIdeSetup extends SleighStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SleighRuntimeModule(), new SleighIdeModule()));
	}
	
}
